# Generated by Django 5.0.9 on 2024-11-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bio_profile_birth_day_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='is_verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='is_verified_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
