# Generated by Django 5.0.9 on 2024-11-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('admin', 'Administrateur'), ('operator', 'Opérateur de transaction')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='verification_code',
            field=models.BooleanField(default=False),
        ),
    ]
