services:
  docs:
    image: cash_send_local_docs
    container_name: cash_send_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./cash_send:/app/cash_send:z
    ports:
      - '9000:9000'
    command: /start-docs
