# Generated by Django 5.0.9 on 2024-10-11 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True)),
                ('date_of_update', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('sender_account_id', models.EmailField(max_length=100, verbose_name='sender')),
                ('receiver_account_id', models.CharField(max_length=100, verbose_name='receiver')),
                ('price', models.IntegerField(verbose_name='montant')),
                ('devise', models.CharField(choices=[('EURO', 'euro'), ('FCFA', 'fcfa'), ('DOLLARS', 'dollars')])),
                ('statut', models.CharField(choices=[('EN_COURS', 'en_cours'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')])),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_creation'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True)),
                ('date_of_update', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.TextField(max_length=300)),
                ('as_read', models.BooleanField(default=False)),
                ('transaction_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'ordering': ['-transaction_id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True)),
                ('date_of_update', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('sender_account_id', models.EmailField(max_length=100, verbose_name='sender')),
                ('receiver_account_id', models.CharField(max_length=100, verbose_name='receiver')),
                ('statut_new_history_transaction', models.CharField(choices=[('EN_COURS', 'en_cours'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')])),
                ('statut_last_history_transaction', models.CharField(choices=[('EN_COURS', 'en_cours'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')])),
                ('transaction_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'ordering': ['-statut_last_history_transaction'],
            },
        ),
    ]
