# Generated by Django 5.0.9 on 2024-11-05 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('date_of_creation', models.DateTimeField(auto_created=True)),
                ('date_of_update', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('code', models.CharField(choices=[('EURO', 'euro'), ('FCFA', 'fcfa'), ('DOLLARS', 'dollars'), ('ROUBLE', 'RUB')])),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='devise',
            field=models.CharField(choices=[('EURO', 'euro'), ('FCFA', 'fcfa'), ('DOLLARS', 'dollars'), ('ROUBLE', 'RUB')]),
        ),
    ]
